#!/usr/bin/env bash
set -Eeuo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run this installer with: sudo ./install.sh"
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP=/opt/trafficlight
CONF=/etc/trafficlight
LOG=/var/log/trafficlight
SVC_USER=trafficlightsvc
TARGET_HOSTNAME=trafficlight
MQTT_ADDR=10.77.0.1
MQTT_PORT=1883
JUNCTION=v1
for arg in "$@"; do
  case "$arg" in
    --t3) JUNCTION=t3 ;;
    *) echo "ERROR: unknown option $arg (supported: --t3)"; exit 1 ;;
  esac
done

step(){ printf '\n\033[1;36m== %s ==\033[0m\n' "$*"; }
pass(){ printf '\033[1;32m[PASS]\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m[WARN]\033[0m %s\n' "$*"; }
fail(){ printf '\033[1;31m[FAIL]\033[0m %s\n' "$*"; exit 1; }

on_error(){
  local rc=$?
  echo
  echo "INSTALL FAILED (exit $rc) at line ${BASH_LINENO[0]}."
  echo "Useful diagnostics:"
  echo "  sudo systemctl status mosquitto --no-pager -l"
  echo "  sudo journalctl -u mosquitto -n 50 --no-pager"
  echo "  sudo systemctl status trafficlight --no-pager -l"
  exit "$rc"
}
trap on_error ERR

step "Install OS packages"
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  python3 python3-venv python3-pip python3-pytest \
  mosquitto mosquitto-clients git network-manager \
  udev iproute2 iputils-ping coreutils grep sed gawk findutils hostname systemd
pass "OS packages installed"

step "Create service account"
if ! id "$SVC_USER" >/dev/null 2>&1; then
  useradd --system --create-home --home-dir /var/lib/trafficlight --shell /usr/sbin/nologin "$SVC_USER"
fi
usermod -a -G dialout "$SVC_USER"
pass "Service account $SVC_USER ready"

step "Install application"
STAGE="$(mktemp -d)"
cleanup(){ rm -rf "$STAGE"; }
trap cleanup EXIT
cp -a "$ROOT"/. "$STAGE"/
rm -rf "$APP"
mkdir -p "$APP" "$CONF" "$LOG"
cp -a "$STAGE"/. "$APP"/
rm -rf "$APP/.git" "$APP/.pytest_cache"
find "$APP" -type d -name __pycache__ -prune -exec rm -rf {} + 2>/dev/null || true
find "$APP" -type f -name '*.py[co]' -delete 2>/dev/null || true

python3 -m venv "$APP/.venv"
"$APP/.venv/bin/python" -m pip install --upgrade pip
"$APP/.venv/bin/pip" install -r "$APP/requirements.txt"
"$APP/.venv/bin/pip" install pytest
pass "Production virtualenv ready"

step "Run application tests"
PYTHONPATH="$APP/raspberry_pi" "$APP/.venv/bin/python" -m pytest -q "$APP/tests"
"$APP/.venv/bin/python" -m json.tool "$APP/config/settings.example.json" >/dev/null
"$APP/.venv/bin/python" -m json.tool "$APP/config/settings.t3.example.json" >/dev/null
for f in "$APP/install.sh" "$APP"/scripts/*.sh; do bash -n "$f"; done
pass "Python tests, JSON and shell syntax passed"

step "Install configuration"
if [[ "$JUNCTION" == "t3" ]]; then
  EXAMPLE="$APP/config/settings.t3.example.json"
else
  EXAMPLE="$APP/config/settings.example.json"
fi
if [[ ! -f "$CONF/settings.json" ]]; then
  if [[ "$JUNCTION" == "t3" ]]; then
    # Start with no lane: the web UI setup wizard adds lanes one by one.
    "$APP/.venv/bin/python" - "$EXAMPLE" "$CONF/settings.json" <<'PYCFG'
import json, sys
cfg = json.load(open(sys.argv[1], encoding="utf-8"))
cfg["lanes"], cfg["sensors"] = [], {}
json.dump(cfg, open(sys.argv[2], "w", encoding="utf-8"), ensure_ascii=False, indent=2)
PYCFG
  else
    cp "$EXAMPLE" "$CONF/settings.json"
  fi
  pass "Created $CONF/settings.json from $(basename "$EXAMPLE")"
else
  warn "Keeping existing $CONF/settings.json"
  if [[ "$JUNCTION" == "t3" ]] && ! grep -q '"junction_type"[[:space:]]*:[[:space:]]*"t3"' "$CONF/settings.json"; then
    warn "Existing settings.json is not a T3 config. To switch: sudo cp $EXAMPLE $CONF/settings.json"
  fi
fi
chown -R "$SVC_USER":"$SVC_USER" "$LOG"
chmod 750 "$LOG"

step "Set hostname safely"
# Update /etc/hosts before hostnamectl so sudo/local resolution is never left broken.
if grep -qE '^127\.0\.1\.1[[:space:]]+' /etc/hosts; then
  sed -i -E "s/^127\.0\.1\.1.*/127.0.1.1\t${TARGET_HOSTNAME}/" /etc/hosts
else
  printf '127.0.1.1\t%s\n' "$TARGET_HOSTNAME" >> /etc/hosts
fi
hostnamectl set-hostname "$TARGET_HOSTNAME"
getent hosts "$TARGET_HOSTNAME" >/dev/null || fail "hostname $TARGET_HOSTNAME does not resolve locally"
pass "Hostname set to $TARGET_HOSTNAME"

step "Configure isolated display Ethernet"
"$APP/scripts/setup_ethernet.sh"
ip -4 addr show eth0 | grep -q '10\.77\.0\.1/24' || fail "eth0 did not receive 10.77.0.1/24"
if [[ "$(cat /sys/class/net/eth0/operstate 2>/dev/null || true)" != "up" ]]; then
  warn "eth0 has no physical link yet (normal if LAN cable/switch is not connected)"
fi
pass "eth0 private address is 10.77.0.1/24"

step "Configure MQTT broker"
# Always replace our drop-in with the known-good minimal Bookworm config.
# Do NOT duplicate persistence/persistence_location from Debian's main config.
mkdir -p /etc/mosquitto/conf.d
cat > /etc/mosquitto/conf.d/trafficlight.conf <<MOSQ
# Auto-generated by E-Car Traffic Light installer.
# Private ESP32 display LAN only.
listener ${MQTT_PORT} ${MQTT_ADDR}
allow_anonymous true
MOSQ

# Mosquitto binds specifically to 10.77.0.1. On Bookworm/NetworkManager,
# systemd can start Mosquitto before the static eth0 address exists during boot.
# Add a drop-in that waits for the private address before the broker starts.
mkdir -p /etc/systemd/system/mosquitto.service.d
cat > /etc/systemd/system/mosquitto.service.d/trafficlight-network.conf <<'MOSQUNIT'
[Unit]
After=NetworkManager.service network-online.target
Wants=network-online.target

[Service]
ExecStartPre=/bin/sh -c 'i=0; while [ $i -lt 60 ]; do ip -4 addr show dev eth0 | grep -q "10.77.0.1/24" && exit 0; i=$((i+1)); sleep 1; done; echo "trafficlight: eth0 10.77.0.1/24 not ready" >&2; exit 1'
MOSQUNIT

systemctl daemon-reload
systemctl enable mosquitto >/dev/null
systemctl reset-failed mosquitto 2>/dev/null || true
systemctl restart mosquitto
for _ in {1..20}; do
  systemctl is-active --quiet mosquitto && break
  sleep 0.25
done
systemctl is-active --quiet mosquitto || fail "Mosquitto did not start"
ss -lnt | grep -q "${MQTT_ADDR}:${MQTT_PORT}" || fail "Mosquitto is not listening on ${MQTT_ADDR}:${MQTT_PORT}"

# Functional local publish/subscribe smoke test.
MQTT_TMP="$(mktemp)"
timeout 5 mosquitto_sub -h "$MQTT_ADDR" -p "$MQTT_PORT" -t '__trafficlight_install_test__' -C 1 >"$MQTT_TMP" &
SUB_PID=$!
sleep 0.4
mosquitto_pub -h "$MQTT_ADDR" -p "$MQTT_PORT" -t '__trafficlight_install_test__' -m 'INSTALL_OK'
wait "$SUB_PID"
grep -qx 'INSTALL_OK' "$MQTT_TMP" || fail "MQTT publish/subscribe smoke test failed"
rm -f "$MQTT_TMP"
pass "Mosquitto active and MQTT loopback test passed"

step "Install systemd service"
cp "$APP/install/trafficlight.service" /etc/systemd/system/trafficlight.service
systemctl daemon-reload
# Sensors are intentionally not required during installation. Leave the
# controller disabled/stopped until S1-S4 USB-RS485 mappings exist. The mapping
# wizard enables autostart only after all four stable symlinks are verified.
if [[ "$JUNCTION" == "t3" ]]; then
  # T3: the controller must run during web setup (port probe, display test).
  # With no lane configured it never controls traffic: every display shows CONFIG.
  systemctl enable trafficlight >/dev/null
  systemctl restart trafficlight
  pass "trafficlight.service running (CONFIG mode until lanes are set up in the web UI)"
else
  systemctl disable trafficlight >/dev/null 2>&1 || true
  systemctl stop trafficlight 2>/dev/null || true
  pass "trafficlight.service installed (disabled/stopped until sensor mapping)"
fi

if [[ "$JUNCTION" == "t3" ]]; then
  step "Install T3 web UI"
  # The web UI writes settings.json, versions/, users.json and audit.log.
  mkdir -p "$CONF/versions"
  chown -R "$SVC_USER":"$SVC_USER" "$CONF"
  chmod 750 "$CONF"
  # Only the reboot command is allowed without a password.
  cat > /etc/sudoers.d/trafficlight-web <<SUDO
${SVC_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl reboot
SUDO
  chmod 440 /etc/sudoers.d/trafficlight-web
  visudo -cf /etc/sudoers.d/trafficlight-web >/dev/null || fail "sudoers snippet invalid"
  cat > /usr/local/bin/trafficlight-user <<USERCLI
#!/usr/bin/env bash
# Manage web UI accounts:  sudo trafficlight-user add <name> --role editor|viewer
set -e
PYTHONPATH=${APP}/raspberry_pi ${APP}/.venv/bin/python -m trafficlight.web.users --data-dir ${CONF} "\$@"
[[ -f ${CONF}/users.json ]] && chown ${SVC_USER}:${SVC_USER} ${CONF}/users.json && chmod 640 ${CONF}/users.json || true
USERCLI
  chmod 755 /usr/local/bin/trafficlight-user
  cp "$APP/install/trafficlight-web.service" /etc/systemd/system/trafficlight-web.service
  systemctl daemon-reload
  systemctl enable trafficlight-web >/dev/null
  systemctl restart trafficlight-web
  sleep 1
  systemctl is-active --quiet trafficlight-web || fail "trafficlight-web did not start (journalctl -u trafficlight-web)"
  pass "trafficlight-web.service active on port 8080"
fi

step "Final installer self-check"
PYTHONPATH="$APP/raspberry_pi" "$APP/.venv/bin/python" -m pytest -q "$APP/tests"
systemctl is-active --quiet mosquitto || fail "Mosquitto unexpectedly inactive"
if [[ "$JUNCTION" != "t3" ]] && systemctl is-enabled --quiet trafficlight; then
  fail "trafficlight.service should remain disabled before sensor mapping"
fi
getent hosts "$TARGET_HOSTNAME" >/dev/null || fail "hostname resolution check failed"
ip -4 addr show eth0 | grep -q '10\.77\.0\.1/24' || fail "Ethernet address check failed"
pass "All installation checks passed"

if [[ "$JUNCTION" == "t3" ]]; then
cat <<T3DONE

============================================================
 T3 JUNCTION MODE
============================================================
 1) Create the first web account (editor):
      sudo trafficlight-user add engineer01 --role editor
 2) Plug in the USB-485 adapters, sensors and displays, then open
      http://<pi-ip>:8080  and log in. The setup page opens:
      press + to add each lane, choose Auto / Manual, the display
      (press "test" - the blinking display is the one) and the sensor
      ports ("find by hand" - cover the sensor and the port is picked).
      Press Next, then drag the lanes onto the map.
 3) The controller is already running; until step 2 is saved every
    display shows CONFIG and no lane gets green.
 4) First flash each ESP32 display by USB (once):
      cd esp32_display_t3 && pio run -e t3_display1 -t upload
    After that, firmware can be updated from the web (OTA).
    Change OTA_PASSWORD in include/device_config.h AND
    "ota.password" in settings.json to the same new value.
 NOTE: T3 logic is tested by simulation only - NOT field-tested yet.
============================================================
T3DONE
  exit 0
fi

cat <<'DONE'

============================================================
 E-CAR TRAFFIC LIGHT INSTALL COMPLETE
============================================================
Pi software + MQTT are READY.
No sensor is required to be connected during installation.
The traffic controller is intentionally NOT started yet.

NEXT, when hardware is available:
  1) Optional Wi-Fi profiles:
       sudo /opt/trafficlight/scripts/setup_wifi.sh
  2) Plug USB-RS485 adapters and run the S1-S4 mapping wizard:
       sudo /opt/trafficlight/scripts/generate_udev_rules.sh
     (When all 4 mappings verify, the wizard enables + starts autostart.)
  3) Check:
       /opt/trafficlight/scripts/friday_preflight.sh
  4) Live log:
       sudo journalctl -u trafficlight -f
  5) Display-only MQTT test:
       /opt/trafficlight/scripts/display_test.sh

NOTE: eth0 may show DOWN until a LAN cable/switch is connected.
      The static address 10.77.0.1/24 is still correctly configured.
============================================================
DONE
